/**
 * One-time / repeatable seed importer.
 *
 * Imports grades.json, subjects.json, academic_calendar.json,
 * documents.json, and curriculum.json into Firestore. All five are real
 * data extracted from the official DCTE PDF (see ../import_dcte_pdf.ts and
 * README.md "Initial Content Import") — `subjects.schema-example.json` /
 * `curriculum.schema-example.json` in this folder are field-shape
 * references only, never imported.
 *
 * IMPORTANT — curriculum rows are never auto-published: every row in
 * curriculum.json carries `needsVerification`. Rows still marked `true`
 * (currently ALL of them — none have been human-reviewed yet) are written
 * to `curriculum_pending`, an admin-only collection the public app never
 * reads. Only a row an admin has explicitly reviewed and promoted (via the
 * `approveCurriculumRecord` callable) ever reaches the public `curriculum`
 * collection the Android app queries. See `importCurriculum` below for
 * exactly how this split works, and README.md §9 for the review workflow.
 *
 * Usage:
 *   1. Download a service-account key for your Firebase project (Firebase
 *      Console > Project Settings > Service Accounts > Generate new
 *      private key). NEVER commit this file.
 *   2. GOOGLE_APPLICATION_CREDENTIALS=/path/to/serviceAccountKey.json \
 *        npx ts-node scripts/seed/import_seed.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { initializeApp, applicationDefault } from 'firebase-admin/app';
import { getFirestore, Timestamp, FieldValue } from 'firebase-admin/firestore';
import { validateRecord, classifyConfidence, findDuplicateKeys, ClassifiableRecord } from './confidence';

initializeApp({ credential: applicationDefault() });
const db = getFirestore();

/** Firestore batched writes cap at 500 mutations — chunk larger sets. */
async function commitInChunks<T>(items: T[], write: (batch: FirebaseFirestore.WriteBatch, item: T) => void) {
  const CHUNK_SIZE = 450;
  for (let i = 0; i < items.length; i += CHUNK_SIZE) {
    const batch = db.batch();
    for (const item of items.slice(i, i + CHUNK_SIZE)) write(batch, item);
    await batch.commit();
  }
}

function readJsonIfExists<T>(filename: string): T[] {
  const filePath = path.join(__dirname, filename);
  if (!fs.existsSync(filePath)) return [];
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function buildKeywords(text: string): string[] {
  return Array.from(
    new Set(
      text
        .toLowerCase()
        .replace(/[^a-z0-9؀-ۿ\s]/g, ' ')
        .split(/\s+/)
        .filter((t) => t.length > 1),
    ),
  );
}

async function importGrades() {
  const grades = readJsonIfExists<Record<string, unknown>>('grades.json');
  for (const g of grades) {
    const { gradeId, displayName, ...rest } = g as any;
    await db
      .collection('grades')
      .doc(gradeId)
      .set({ ...rest, displayName, searchKeywords: buildKeywords(displayName) }, { merge: true });
  }
  console.log(`Imported ${grades.length} grades.`);
}

async function importSubjects() {
  const subjects = readJsonIfExists<Record<string, unknown>>('subjects.json');
  for (const s of subjects) {
    const { subjectId, name, ...rest } = s as any;
    if (String(name).startsWith('REPLACE WITH')) {
      throw new Error(`subjects.json contains an unfilled template row for ${subjectId}. Fill in real data first.`);
    }
    await db
      .collection('subjects')
      .doc(subjectId)
      .set({ ...rest, name, searchKeywords: buildKeywords(name) }, { merge: true });
  }
  console.log(`Imported ${subjects.length} subjects.`);
}

async function importAcademicCalendar() {
  const rows = readJsonIfExists<Record<string, unknown>>('academic_calendar.json');
  for (const r of rows as any[]) {
    const { calendarId, startDate, endDate, ...rest } = r;
    await db
      .collection('academic_calendar')
      .doc(calendarId)
      .set(
        {
          ...rest,
          startDate: Timestamp.fromDate(new Date(startDate)),
          endDate: Timestamp.fromDate(new Date(endDate)),
        },
        { merge: true },
      );
  }
  console.log(`Imported ${rows.length} academic calendar rows.`);
}

async function importDocuments() {
  const docs = readJsonIfExists<Record<string, unknown>>('documents.json');
  for (const d of docs as any[]) {
    const { documentId, title, ...rest } = d;
    await db
      .collection('documents')
      .doc(documentId)
      .set(
        {
          ...rest,
          title,
          searchKeywords: buildKeywords(title),
          createdAt: FieldValue.serverTimestamp(),
          updatedAt: FieldValue.serverTimestamp(),
        },
        { merge: true },
      );
  }
  console.log(`Imported ${docs.length} document records.`);
}

/**
 * Curriculum rows are never auto-published: `curriculum.json` (whether
 * generated by scripts/import_dcte_pdf.ts or edited by hand) carries a
 * `needsVerification` flag on every row. This importer honors it —
 *
 *   needsVerification: true  -> `curriculum_pending` (admin-only, see
 *                                firebase/firestore.rules) for review
 *   needsVerification: false -> `curriculum` (the public, app-facing
 *                                collection) — only rows a human has
 *                                actually confirmed against the source PDF
 *
 * Every pending row also gets `extractionConfidence` (HIGH/MEDIUM/LOW) and
 * a `validation` report computed here (see ./confidence.ts — the single
 * place this logic lives; the admin dashboard and bulk-approve Cloud
 * Functions only ever read these fields back, never recompute them), plus
 * the review-workflow fields (`verificationStatus`, `reviewedBy`,
 * `reviewedAt`, `correctedValue`, `originalExtractedValue`) starting
 * empty. `rawText`/`extractedText`/`structuredData` are captured as
 * explicit, permanently-immutable snapshots of what was actually
 * extracted, distinct from `unitTitle` (also never mutated by this
 * importer — corrections live only in `correctedValue`, applied by an
 * admin, see functions/src/admin/adminApi.ts).
 *
 * An admin promotes a reviewed row from pending to public via the
 * `approveCurriculumRecord` callable, the same detected -> pending_review
 * -> verified -> published shape used for whole documents — and that
 * function COPIES rather than deletes the pending row, so
 * `curriculum_pending` remains a permanent audit trail of every review
 * decision. Running this importer again after re-generating
 * curriculum.json does not un-approve anything already promoted — it only
 * touches `curriculum_pending` doc IDs matching the current file, and
 * never overwrites one already reviewed (`verificationStatus !==
 * 'pending_review'`), so re-running the importer can't silently wipe out
 * review history.
 */
async function importCurriculum() {
  const rows = readJsonIfExists<ClassifiableRecord & Record<string, unknown>>('curriculum.json');
  const gradeIds = new Set(readJsonIfExists<{ gradeId: string }>('grades.json').map((g) => g.gradeId));
  const subjectIds = new Set(readJsonIfExists<{ subjectId: string }>('subjects.json').map((s) => s.subjectId));
  const documentIds = new Set(readJsonIfExists<{ documentId: string }>('documents.json').map((d) => d.documentId));
  const duplicateKeys = findDuplicateKeys(rows);

  const publicRows: any[] = [];
  const pendingRows: any[] = [];
  const confidenceCounts = { HIGH: 0, MEDIUM: 0, LOW: 0 };

  for (const r of rows as any[]) {
    const { curriculumId, unitTitle, needsVerification, ...rest } = r;
    if (String(unitTitle).startsWith('REPLACE WITH')) {
      throw new Error(`curriculum.json contains an unfilled template row for ${curriculumId}. Fill in real data first.`);
    }

    if (needsVerification === false) {
      publicRows.push({
        curriculumId,
        data: {
          ...rest,
          unitTitle,
          needsVerification: false,
          searchKeywords: buildKeywords(unitTitle),
          createdAt: FieldValue.serverTimestamp(),
          updatedAt: FieldValue.serverTimestamp(),
        },
      });
      continue;
    }

    const validation = validateRecord(r, gradeIds, subjectIds, documentIds, duplicateKeys);
    const extractionConfidence = classifyConfidence(r, validation);
    confidenceCounts[extractionConfidence]++;

    // Only ever create/refresh a pending row that's still `pending_review`
    // — an existing 'verified'/'rejected' row (an admin already decided)
    // is left completely untouched by re-running the importer.
    const existing = await db.collection('curriculum_pending').doc(curriculumId).get();
    if (existing.exists && existing.data()?.verificationStatus !== 'pending_review') {
      continue;
    }

    pendingRows.push({
      curriculumId,
      data: {
        ...rest,
        unitTitle,
        needsVerification: true,
        extractionConfidence,
        validation,
        verificationStatus: 'pending_review',
        reviewedBy: null,
        reviewedAt: null,
        originalExtractedValue: null,
        correctedValue: null,
        correctedBy: null,
        correctedAt: null,
        // Immutable snapshots of exactly what was extracted — never
        // touched again after this import, regardless of later corrections.
        rawText: unitTitle,
        extractedText: unitTitle,
        structuredData: {
          gradeId: rest.gradeId,
          subjectId: rest.subjectId,
          semester: rest.semester,
          unitNumber: rest.unitNumber,
        },
        searchKeywords: buildKeywords(unitTitle),
        createdAt: FieldValue.serverTimestamp(),
        updatedAt: FieldValue.serverTimestamp(),
      },
    });
  }

  await commitInChunks(publicRows, (batch, row) =>
    batch.set(db.collection('curriculum').doc(row.curriculumId), row.data, { merge: true }),
  );
  await commitInChunks(pendingRows, (batch, row) =>
    batch.set(db.collection('curriculum_pending').doc(row.curriculumId), row.data, { merge: true }),
  );

  console.log(
    `Imported ${rows.length} curriculum rows: ${publicRows.length} verified -> curriculum (public), ` +
      `${pendingRows.length} unverified -> curriculum_pending (admin review required, never shown in the app).`,
  );
  console.log(
    `Pending confidence breakdown: HIGH ${confidenceCounts.HIGH}, MEDIUM ${confidenceCounts.MEDIUM}, LOW ${confidenceCounts.LOW}.`,
  );
}

async function main() {
  await importGrades();
  await importSubjects();
  await importAcademicCalendar();
  await importDocuments();
  await importCurriculum();
  await db.collection('app_config').doc('global').set(
    { lastSyncedAt: FieldValue.serverTimestamp(), currentSession: '2025-26' },
    { merge: true },
  );
  console.log('Seed import complete.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
